server:
    port: ${PORT:8080}

logging:
    level:
        org:
            atmosphere: warn

vaadin:
    allowed-packages: com.vaadin,org.vaadin,com.flowingcode,app.k12onos.tickets

spring:
    application:
        name: tickets
    
    datasource:
        url: ${DB_URL}
    
    jpa:
        properties:
            hibernate:
                default_schema: app

    flyway:
        default-schema: app
        schemas:
            - app
    
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KC_ISSUER_URL}
            
            client:
                registration:
                    keycloak:
                        provider: keycloak
                        client-id: ${KC_CLIENT_ID}
                        client-secret: ${KC_CLIENT_SECRET}
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                        scope: openid,profile
                
                provider:
                    keycloak:
                        issuer-uri: ${KC_ISSUER_URL}

tickets:
    hmac-secret: ${HMAC_SECRET}

s3:
    service-role-key: ${S3_SERVICE_ROLE_KEY}
    public-base-url: ${S3_PUBLIC_BASE_URL}
    bucket:
        event-assets: ${S3_EVENT_ASSETS_BUCKET}
