server:
    port: ${PORT:8080}

logging:
    level:
        org:
            atmosphere: warn

vaadin:
    launch-browser: true
    allowed-packages: com.vaadin,org.vaadin,com.flowingcode,app.k12onos.tickets

spring:
    application:
        name: tickets
    
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: changemeinprod!
    
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9090/realms/event-ticket-platform
            
            client:
                registration:
                    keycloak:
                        provider: keycloak
                        client-id: event-ticket-platform-app
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                        scope: openid,profile
                
                provider:
                    keycloak:
                        issuer-uri: http://localhost:9090/realms/event-ticket-platform
                        authorization-uri: http://localhost:9090/realms/event-ticket-platform/protocol/openid-connect/auth
                        user-info-uri: http://localhost:9090/realms/event-ticket-platform/protocol/openid-connect/userinfo
                        token-uri: http://localhost:9090/realms/event-ticket-platform/protocol/openid-connect/token
