server:
    port: ${PORT:8080}

logging:
    level:
        org:
            atmosphere: warn

vaadin:
    allowed-packages: com.vaadin,org.vaadin,com.flowingcode,app.k12onos.tickets

spring:
    application:
        name: tickets
    
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?user=postgres&password=changemeinprod!}
    
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KC_ISSUER_URL:http://localhost:9090/realms/event-ticket-platform}
            
            client:
                registration:
                    keycloak:
                        provider: keycloak
                        client-id: ${KC_CLIENT_ID:event-ticket-platform-app}
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                        scope: openid,profile
                
                provider:
                    keycloak:
                        issuer-uri: ${KC_ISSUER_URL:http://localhost:9090/realms/event-ticket-platform}

tickets:
    hmac-secret: ${HMAC_SECRET}

s3:
    endpoint: ${S3_ENDPOINT_URL}
    region: ${S3_REGION}
    access-key-id: ${S3_ACCESS_KEY_ID}
    secret-access-key: ${S3_SECRET_ACCESS_KEY}
    service-role-key: ${S3_SERVICE_ROLE_KEY}
    public-base-url: ${S3_PUBLIC_BASE_URL}
    bucket:
        event-assets: ${S3_EVENT_ASSETS_BUCKET}
